services:
  fastapi:
    build: ./
    volumes:
      - ./src:/app/src
      - ./start.sh:/app/start.sh
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - monitoring-net


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring-net

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    ports:
      - "8428:8428"
    volumes:
      - ./victoriametrics/scrape.yml:/etc/vm/scrape.yml
      - vm-data:/victoria-metrics-data
    command:
      - '--promscrape.config=/etc/vm/scrape.yml'
      - '--storageDataPath=/victoria-metrics-data'
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - victoriametrics
    networks:
      - monitoring-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring-net
    volumes:
      - loki-data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring-net
    depends_on:
      - loki

volumes:
  vm-data:
  grafana-data:
  loki-data:

networks:
  monitoring-net:
    driver: bridge